-- CREAMOS LA BASE DE DATOS DEVSWAP
CREATE DATABASE DEVSWAP;

-- CREAMOS LAS TABLAS CON LOS CAMPOS CORRESPONDIENTES
CREATE TABLE ADMINISTRADOR (
    CORREO_A VARCHAR(50) NOT NULL,
    NICK_A VARCHAR(10),
    CONTRASEÑA_A VARCHAR(100),
    PRIMARY KEY(CORREO_A)
);

CREATE TABLE CATEGORIA (
    NOMBRE_C VARCHAR(50) NOT NULL,
    DESCRIPCION VARCHAR(50),
    IMAGEN_C VARBINARY(MAX),
    PRIMARY KEY(NOMBRE_C)
);

CREATE TABLE USUARIO (
    CORREO_U VARCHAR(50) NOT NULL,
    NICK_U VARCHAR(10),
    APELLIDO1 VARCHAR(10),
    APELLIDO2 VARCHAR(10),
    NOMBRE_U VARCHAR(10),
    TELEFONO INT,
    CIUDAD VARCHAR(20),
    CONTRASEÑA_U VARCHAR(100),
    PRIMARY KEY(CORREO_U)
);

CREATE TABLE PUBLICACION1(
    ID_P VARCHAR(10) NOT NULL,
    CORREO_U VARCHAR(50) NOT NULL,
    NOMBRE_C VARCHAR(50) NOT NULL,
    PRIMARY KEY(ID_P, CORREO_U, NOMBRE_C),
    FOREIGN KEY(CORREO_U) REFERENCES USUARIO(CORREO_U) ON DELETE CASCADE
);

CREATE TABLE PUBLICACION2 (
    ID_P VARCHAR(10) NOT NULL,
    CAMBIO VARCHAR(20),
    ESTADO VARCHAR(10),
    UBICACION VARCHAR(20),
    NOMBRE_P VARCHAR(20),
    DESCRIPCION VARCHAR(50),
    IMAGEN VARBINARY(MAX),
    PRIMARY KEY(ID_P),
    FOREIGN KEY(ID_P) REFERENCES PUBLICACION1(ID_P) ON DELETE CASCADE
);

CREATE TABLE GESTIONA_U (
    CORREO_U VARCHAR(50) NOT NULL,
    CORREO_A VARCHAR(50) NOT NULL,
    PRIMARY KEY(CORREO_U, CORREO_A),
    FOREIGN KEY(CORREO_U) REFERENCES USUARIO(CORREO_U) ON DELETE CASCADE
);

CREATE TABLE SOLICITA (
    CORREO_U VARCHAR(50) NOT NULL,
    ID_P VARCHAR(10) NOT NULL,
    CALIFICACION FLOAT,
    FECHA DATE,
    ESTADO VARCHAR(50),
    PRIMARY KEY(CORREO_U, ID_P),
    FOREIGN KEY(CORREO_U) REFERENCES USUARIO(CORREO_U) ON DELETE CASCADE,
    FOREIGN KEY(ID_P) REFERENCES PUBLICACION1(ID_P) ON DELETE CASCADE
);

CREATE TABLE GESTIONA_C (
    CORREO_A VARCHAR(50) NOT NULL,
    NOMBRE_C VARCHAR(50) NOT NULL,
    PRIMARY KEY(CORREO_A, NOMBRE_C),
    FOREIGN KEY(NOMBRE_C) REFERENCES CATEGORIA(NOMBRE_C) ON DELETE CASCADE
);

-- UNA VEZ CREADA LA ESTRUCTURA, ALMACENAMOS DATOS DE PRUEBA
INSERT INTO ADMINISTRADOR(CORREO_A, NICK_A, CONTRASEÑA_A)
VALUES
('LUISADMIN@GMAIL.COM', 'ADMINPRO', 'LUIS123'),
('PEDRO@GMAIL.COM', 'PEDROADMIN', 'PEDROADMIN123'),
('MARIO@HOTMAIL.COM', 'MARIOG', 'MARIOG');

INSERT INTO CATEGORIA(NOMBRE_C, DESCRIPCION, IMAGEN_C)
VALUES
('ACCESORIOS', 'ACCESORIOS: CASCOS, TECLADOS..',''),
('PORTATILES', 'PORTATILES DE TODAS LAS MARCAS', ''),
('TABLETS', 'TABLES DE TODAS LAS MARCAS', ''),
('SMARTPHONES', 'SMARTPHONES DE TODAS LAS MARCAS', ''),
('LIBROS', 'LIBROS ORIENTADOS A LA PROGRAMACIÓN', '');

INSERT INTO USUARIO(CORREO_U, NICK_U, APELLIDO1, APELLIDO2, NOMBRE_U, TELEFONO, CIUDAD, CONTRASEÑA_U)
VALUES
('HUGOUSER@GMAIL.COM', 'HUGOPRO', 'GONZALEZ', 'PEREZ', 'HUGO', 1234, 'VALLADOLID', 'HUGOPRO'),
('SARAUSER@HOTMAIL.COM', 'SARAGARCIA', 'GARCIA', 'HERNANDEZ', 'SARA', 4567, 'MADRID', 'SARA123'),
('SERGIO12@GMAIL.COM', 'SERGIO12', 'BUENO', 'DIAZ', 'SERGIO', 1234567, 'BARCELONA', 'SERGIO12');