-- CREAMOS LA BASE DE DATOS DEVSWAP
CREATE DATABASE IF NOT EXISTS DEVSWAP;
USE DEVSWAP;

-- CREAMOS LAS TABLAS CON LOS CAMPOS CORRESPONDIENTES
CREATE TABLE ADMINISTRADOR (
    CORREO_A VARCHAR(50) NOT NULL,
    NICK_A VARCHAR(10),
    CONTRASEÑA_A VARCHAR(100),
    PRIMARY KEY(CORREO_A)
);

CREATE TABLE CATEGORIA (
    NOMBRE_C VARCHAR(50) NOT NULL,
    DESCRIPCION_C VARCHAR(100),
    IMAGEN_C VARCHAR(255),
    PRIMARY KEY(NOMBRE_C)
);

CREATE TABLE USUARIO (
    CORREO_U VARCHAR(50) NOT NULL,
    NICK_U VARCHAR(10),
    APELLIDO1 VARCHAR(10),
    APELLIDO2 VARCHAR(10),
    NOMBRE_U VARCHAR(10),
    TELEFONO INT,
    CIUDAD VARCHAR(20),
    CONTRASEÑA_U VARCHAR(100),
    PRIMARY KEY(CORREO_U)
);

CREATE TABLE PUBLICACION1(
    ID_P VARCHAR(10) NOT NULL,
    CORREO_U VARCHAR(50) NOT NULL,
    NOMBRE_C VARCHAR(50) NOT NULL,
    PRIMARY KEY(ID_P, CORREO_U, NOMBRE_C),
    FOREIGN KEY(CORREO_U) REFERENCES USUARIO(CORREO_U) ON DELETE CASCADE,
    FOREIGN KEY(NOMBRE_C) REFERENCES CATEGORIA(NOMBRE_C) ON DELETE CASCADE
);

CREATE TABLE PUBLICACION2 (
    ID_P VARCHAR(10) NOT NULL,
    CAMBIO VARCHAR(100),
    ESTADO VARCHAR(10),
    UBICACION VARCHAR(20),
    NOMBRE_P VARCHAR(100),
    DESCRIPCION_P VARCHAR(100),
    IMAGEN_P VARCHAR(255),
    PRIMARY KEY(ID_P),
    FOREIGN KEY(ID_P) REFERENCES PUBLICACION1(ID_P) ON DELETE CASCADE
);

CREATE TABLE GESTIONA_U (
    CORREO_U VARCHAR(50) NOT NULL,
    CORREO_A VARCHAR(50) NOT NULL,
    PRIMARY KEY(CORREO_U, CORREO_A),
    FOREIGN KEY(CORREO_U) REFERENCES USUARIO(CORREO_U) ON DELETE CASCADE,
    FOREIGN KEY(CORREO_A) REFERENCES ADMINISTRADOR(CORREO_A) ON DELETE CASCADE
);

CREATE TABLE SOLICITA (
    CORREO_U VARCHAR(50) NOT NULL,
    ID_P VARCHAR(10) NOT NULL,
    CALIFICACION FLOAT,
    FECHA DATE,
    ESTADO VARCHAR(50),
    PRIMARY KEY(CORREO_U, ID_P),
    FOREIGN KEY(CORREO_U) REFERENCES USUARIO(CORREO_U) ON DELETE CASCADE,
    FOREIGN KEY(ID_P) REFERENCES PUBLICACION1(ID_P) ON DELETE CASCADE
);

CREATE TABLE GESTIONA_C (
    CORREO_A VARCHAR(50) NOT NULL,
    NOMBRE_C VARCHAR(50) NOT NULL,
    PRIMARY KEY(CORREO_A, NOMBRE_C),
    FOREIGN KEY(CORREO_A) REFERENCES ADMINISTRADOR(CORREO_A) ON DELETE CASCADE,
    FOREIGN KEY(NOMBRE_C) REFERENCES CATEGORIA(NOMBRE_C) ON DELETE CASCADE
);

-- UNA VEZ CREADA LA ESTRUCTURA, ALMACENAMOS DATOS DE PRUEBA
INSERT INTO ADMINISTRADOR(CORREO_A, NICK_A, CONTRASEÑA_A)
VALUES
('LUISADMIN@GMAIL.COM', 'ADMINPRO', 'LUIS123'),
('PEDRO@GMAIL.COM', 'PEDROADMIN', 'PEDROADMIN123'),
('MARIO@HOTMAIL.COM', 'MARIOG', 'MARIOG');

INSERT INTO CATEGORIA(NOMBRE_C, DESCRIPCION_C, IMAGEN_C)
VALUES
('ACCESORIOS', 'ACCESORIOS: CASCOS, TECLADOS..', 'imagenes/Emoji/emoji_Accesorio.avif'),
('PORTATILES', 'PORTATILES DE TODAS LAS MARCAS', 'imagenes/Emoji/emoji_Portatil.png'),
('TABLETS', 'TABLES DE TODAS LAS MARCAS', 'imagenes/Emoji/emoji_Tablet.jpg'),
('SMARTPHONE', 'SMARTPHONES DE TODAS LAS MARCAS', 'imagenes/Emoji/emoji_telefono.png'),
('LIBROS', 'LIBROS ORIENTADOS A LA PROGRAMACIÓN', 'imagenes/Emoji/emoji_libros.png'),
('AUDIO','OBJETOS RELACIONADOS CON EL AUDIO: CASCOS, ALTAVOCES...', 'imagenes/Emoji/emoji_Audio.webp');

INSERT INTO USUARIO(CORREO_U, NICK_U, APELLIDO1, APELLIDO2, NOMBRE_U, TELEFONO, CIUDAD, CONTRASEÑA_U)
VALUES
('HUGOUSER@GMAIL.COM', 'HUGOPRO', 'GONZALEZ', 'PEREZ', 'HUGO', 1234, 'VALLADOLID', 'HUGOPRO'),
('SARAUSER@HOTMAIL.COM', 'SARAGARCIA', 'GARCIA', 'HERNANDEZ', 'SARA', 4567, 'MADRID', 'SARA123'),
('SERGIO12@GMAIL.COM', 'SERGIO12', 'BUENO', 'DIAZ', 'SERGIO', 1234567, 'BARCELONA', 'SERGIO12');

INSERT INTO PUBLICACION1(ID_P, CORREO_U, NOMBRE_C)
VALUES
('ID001', 'HUGOUSER@GMAIL.COM', 'AUDIO'),
('ID002', 'HUGOUSER@GMAIL.COM', 'SMARTPHONE'),
('ID003', 'SARAUSER@HOTMAIL.COM', 'LIBROS'),
('ID004', 'SARAUSER@HOTMAIL.COM', 'PORTATILES'),
('ID005', 'SERGIO12@GMAIL.COM', 'TABLETS'),
('ID006', 'SERGIO12@GMAIL.COM', 'ACCESORIOS');

INSERT INTO PUBLICACION2(ID_P, CAMBIO, ESTADO, UBICACION, NOMBRE_P, DESCRIPCION_P, IMAGEN_P)
VALUES
('ID001', 'LIBROS DE PROGRAMACION', 'USADO', 'SALAMANCA', 'CASCOS SONY', 'CASCOS DE LA MARCA SONY', 'imagenes/Fotos/cascos.jpg'),
('ID002', 'IPAD AIR', 'NUEVO', 'BARCELONA', 'IPHONE 17 PRO', 'IPHONE NUEVO A ESTRENAR', 'imagenes/Fotos/iPhone.jpg'),  
('ID003', 'TECLADOS DE ORDENADOR', 'USADO', 'MADRID', 'EL PROGRAMADOR PRAGMATICO', 'LIBRO SOBRE PROGRAMACION', 'imagenes/Fotos/libro.jpg'),
('ID004', 'SMARTPHONES NUEVOS', 'RESTAURADO', 'CADIZ', 'MACBOOK PRO', 'PORTATIL DE LA MARCA APPLE', 'imagenes/Fotos/MacBook.jpg'),
('ID005', 'PORTATIL', 'SEMINUEVA', 'VALLADOLID', 'XIAOMI PAD 7', 'TABLET XIAOMI USADA', 'imagenes/Fotos/tablet.jpg'),
('ID006', 'FUNDAS PARA XIAOMI', 'USADO', 'CACERES', 'TECLADO DE LUCES RGB', 'TECLADO CON LUCES PARA GAMING', 'imagenes/Fotos/tecladoRGB.jpg');

INSERT INTO GESTIONA_U (CORREO_U, CORREO_A) 
VALUES
('HUGOUSER@GMAIL.COM', 'LUISADMIN@GMAIL.COM'),
('SARAUSER@HOTMAIL.COM', 'PEDRO@GMAIL.COM'),
('SERGIO12@GMAIL.COM', 'MARIO@HOTMAIL.COM');

INSERT INTO SOLICITA(CORREO_U, ID_P, CALIFICACION, FECHA, ESTADO)
VALUES
('HUGOUSER@GMAIL.COM', 'ID005', 4.5, '2025-12-02', 'ACEPTADO'),
('SARAUSER@HOTMAIL.COM', 'ID001', 3.5, '2026-01-04', 'RECHAZADO');

INSERT INTO GESTIONA_C(CORREO_A, NOMBRE_C)
VALUES
('LUISADMIN@GMAIL.COM', 'ACCESORIOS'),
('LUISADMIN@GMAIL.COM', 'PORTATILES'),
('PEDRO@GMAIL.COM', 'TABLETS'),
('PEDRO@GMAIL.COM', 'SMARTPHONE'),
('MARIO@HOTMAIL.COM', 'LIBROS'),
('MARIO@HOTMAIL.COM', 'AUDIO');